// Generated by gencpp from file bekci/JointVelocity.msg
// DO NOT EDIT!


#ifndef BEKCI_MESSAGE_JOINTVELOCITY_H
#define BEKCI_MESSAGE_JOINTVELOCITY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bekci
{
template <class ContainerAllocator>
struct JointVelocity_
{
  typedef JointVelocity_<ContainerAllocator> Type;

  JointVelocity_()
    : DOF(0)
    , names()
    , velocities()  {
    }
  JointVelocity_(const ContainerAllocator& _alloc)
    : DOF(0)
    , names(_alloc)
    , velocities(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _DOF_type;
  _DOF_type DOF;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _names_type;
  _names_type names;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocities_type;
  _velocities_type velocities;




  typedef boost::shared_ptr< ::bekci::JointVelocity_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bekci::JointVelocity_<ContainerAllocator> const> ConstPtr;

}; // struct JointVelocity_

typedef ::bekci::JointVelocity_<std::allocator<void> > JointVelocity;

typedef boost::shared_ptr< ::bekci::JointVelocity > JointVelocityPtr;
typedef boost::shared_ptr< ::bekci::JointVelocity const> JointVelocityConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bekci::JointVelocity_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bekci::JointVelocity_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bekci

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bekci': ['/home/fatih/git/GuvenlikBekcisi/bekci/src/bekci/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bekci::JointVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bekci::JointVelocity_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::JointVelocity_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::JointVelocity_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::JointVelocity_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::JointVelocity_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bekci::JointVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c001b9923259e52bcef9600eaf6b8f5";
  }

  static const char* value(const ::bekci::JointVelocity_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c001b9923259e52ULL;
  static const uint64_t static_value2 = 0xbcef9600eaf6b8f5ULL;
};

template<class ContainerAllocator>
struct DataType< ::bekci::JointVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bekci/JointVelocity";
  }

  static const char* value(const ::bekci::JointVelocity_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bekci::JointVelocity_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 DOF\n\
string[] names\n\
float64[] velocities\n\
";
  }

  static const char* value(const ::bekci::JointVelocity_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bekci::JointVelocity_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DOF);
      stream.next(m.names);
      stream.next(m.velocities);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointVelocity_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bekci::JointVelocity_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bekci::JointVelocity_<ContainerAllocator>& v)
  {
    s << indent << "DOF: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.DOF);
    s << indent << "names[]" << std::endl;
    for (size_t i = 0; i < v.names.size(); ++i)
    {
      s << indent << "  names[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.names[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEKCI_MESSAGE_JOINTVELOCITY_H
