// Generated by gencpp from file bekci/JointValue.msg
// DO NOT EDIT!


#ifndef BEKCI_MESSAGE_JOINTVALUE_H
#define BEKCI_MESSAGE_JOINTVALUE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bekci
{
template <class ContainerAllocator>
struct JointValue_
{
  typedef JointValue_<ContainerAllocator> Type;

  JointValue_()
    : DOF(0)
    , values()  {
    }
  JointValue_(const ContainerAllocator& _alloc)
    : DOF(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef uint16_t _DOF_type;
  _DOF_type DOF;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _values_type;
  _values_type values;




  typedef boost::shared_ptr< ::bekci::JointValue_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bekci::JointValue_<ContainerAllocator> const> ConstPtr;

}; // struct JointValue_

typedef ::bekci::JointValue_<std::allocator<void> > JointValue;

typedef boost::shared_ptr< ::bekci::JointValue > JointValuePtr;
typedef boost::shared_ptr< ::bekci::JointValue const> JointValueConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bekci::JointValue_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bekci::JointValue_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bekci

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bekci': ['/home/fatih/git/GuvenlikBekcisi/bekci/src/bekci/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bekci::JointValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bekci::JointValue_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::JointValue_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::JointValue_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::JointValue_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::JointValue_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bekci::JointValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d99146da7a6c4ae42eff12882177ba3";
  }

  static const char* value(const ::bekci::JointValue_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d99146da7a6c4aeULL;
  static const uint64_t static_value2 = 0x42eff12882177ba3ULL;
};

template<class ContainerAllocator>
struct DataType< ::bekci::JointValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bekci/JointValue";
  }

  static const char* value(const ::bekci::JointValue_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bekci::JointValue_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 DOF\n\
float64[] values\n\
";
  }

  static const char* value(const ::bekci::JointValue_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bekci::JointValue_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.DOF);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct JointValue_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bekci::JointValue_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bekci::JointValue_<ContainerAllocator>& v)
  {
    s << indent << "DOF: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.DOF);
    s << indent << "values[]" << std::endl;
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      s << indent << "  values[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEKCI_MESSAGE_JOINTVALUE_H
