// Generated by gencpp from file bekci/QuantativeSafetyStatus.msg
// DO NOT EDIT!


#ifndef BEKCI_MESSAGE_QUANTATIVESAFETYSTATUS_H
#define BEKCI_MESSAGE_QUANTATIVESAFETYSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bekci
{
template <class ContainerAllocator>
struct QuantativeSafetyStatus_
{
  typedef QuantativeSafetyStatus_<ContainerAllocator> Type;

  QuantativeSafetyStatus_()
    : joint_status()  {
    }
  QuantativeSafetyStatus_(const ContainerAllocator& _alloc)
    : joint_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _joint_status_type;
  _joint_status_type joint_status;




  typedef boost::shared_ptr< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct QuantativeSafetyStatus_

typedef ::bekci::QuantativeSafetyStatus_<std::allocator<void> > QuantativeSafetyStatus;

typedef boost::shared_ptr< ::bekci::QuantativeSafetyStatus > QuantativeSafetyStatusPtr;
typedef boost::shared_ptr< ::bekci::QuantativeSafetyStatus const> QuantativeSafetyStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bekci::QuantativeSafetyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bekci

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bekci': ['/home/fatih/git/GuvenlikBekcisi/bekci/src/bekci/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "957215486e0af0ae488964248502b403";
  }

  static const char* value(const ::bekci::QuantativeSafetyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x957215486e0af0aeULL;
  static const uint64_t static_value2 = 0x488964248502b403ULL;
};

template<class ContainerAllocator>
struct DataType< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bekci/QuantativeSafetyStatus";
  }

  static const char* value(const ::bekci::QuantativeSafetyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8[] joint_status\n\
";
  }

  static const char* value(const ::bekci::QuantativeSafetyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QuantativeSafetyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bekci::QuantativeSafetyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bekci::QuantativeSafetyStatus_<ContainerAllocator>& v)
  {
    s << indent << "joint_status[]" << std::endl;
    for (size_t i = 0; i < v.joint_status.size(); ++i)
    {
      s << indent << "  joint_status[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.joint_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEKCI_MESSAGE_QUANTATIVESAFETYSTATUS_H
