// Generated by gencpp from file bekci/SpaceSafetyStatus.msg
// DO NOT EDIT!


#ifndef BEKCI_MESSAGE_SPACESAFETYSTATUS_H
#define BEKCI_MESSAGE_SPACESAFETYSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bekci
{
template <class ContainerAllocator>
struct SpaceSafetyStatus_
{
  typedef SpaceSafetyStatus_<ContainerAllocator> Type;

  SpaceSafetyStatus_()
    : sphere_status()  {
    }
  SpaceSafetyStatus_(const ContainerAllocator& _alloc)
    : sphere_status(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int8_t, typename ContainerAllocator::template rebind<int8_t>::other >  _sphere_status_type;
  _sphere_status_type sphere_status;




  typedef boost::shared_ptr< ::bekci::SpaceSafetyStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bekci::SpaceSafetyStatus_<ContainerAllocator> const> ConstPtr;

}; // struct SpaceSafetyStatus_

typedef ::bekci::SpaceSafetyStatus_<std::allocator<void> > SpaceSafetyStatus;

typedef boost::shared_ptr< ::bekci::SpaceSafetyStatus > SpaceSafetyStatusPtr;
typedef boost::shared_ptr< ::bekci::SpaceSafetyStatus const> SpaceSafetyStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bekci::SpaceSafetyStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace bekci

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'bekci': ['/home/fatih/git/GuvenlikBekcisi/bekci/src/bekci/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bekci::SpaceSafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bekci::SpaceSafetyStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bekci::SpaceSafetyStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5525024a991106c89e7d72a280b60a24";
  }

  static const char* value(const ::bekci::SpaceSafetyStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5525024a991106c8ULL;
  static const uint64_t static_value2 = 0x9e7d72a280b60a24ULL;
};

template<class ContainerAllocator>
struct DataType< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bekci/SpaceSafetyStatus";
  }

  static const char* value(const ::bekci::SpaceSafetyStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[]  sphere_status\n\
";
  }

  static const char* value(const ::bekci::SpaceSafetyStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sphere_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpaceSafetyStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bekci::SpaceSafetyStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bekci::SpaceSafetyStatus_<ContainerAllocator>& v)
  {
    s << indent << "sphere_status[]" << std::endl;
    for (size_t i = 0; i < v.sphere_status.size(); ++i)
    {
      s << indent << "  sphere_status[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.sphere_status[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEKCI_MESSAGE_SPACESAFETYSTATUS_H
